# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg_id', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='ChannelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('version', models.CharField(blank=True, default='1.0.0', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SDKInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('status', models.CharField(choices=[('N', 'Normal'), ('B', 'Busy'), ('F', 'Full'), ('S', 'Stop')], max_length=1)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.GameInfo')),
            ],
        ),
        migrations.AddField(
            model_name='appconfig',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ChannelInfo'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.GameInfo'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='sdk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SDKInfo'),
        ),
    ]
