# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='pkg_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='api.GameInfo'),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='status',
            field=models.CharField(choices=[('N', 'Normal'), ('B', 'Busy'), ('F', 'Full'), ('S', 'Stop')], default='N', max_length=1),
        ),
    ]
