# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 07:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20151217_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='name',
            field=models.CharField(default=datetime.datetime(2015, 12, 17, 7, 16, 20, 264361, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
