# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20151217_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='index',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='timeout',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='status',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Busy'), (3, 'Full'), (0, 'Stop')], default=0, max_length=1),
        ),
    ]
