# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20151218_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='timeout',
            field=models.IntegerField(default=10),
        ),
    ]
