# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20151218_0421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverinfo',
            old_name='new',
            new_name='isnew',
        ),
    ]
