# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20151218_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='announcement',
            field=models.TextField(blank=True),
        ),
    ]
