# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_gameinfo_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='activity_pic1',
            field=models.ImageField(default='', upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='activity_pic2',
            field=models.ImageField(default='', upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='activity_pic3',
            field=models.ImageField(default='', upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='status',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Busy'), (3, 'Full'), (0, 'Stop'), (-1, 'Hide')], default=0),
        ),
    ]
