# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-13 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160613_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelinfo',
            name='index',
        ),
        migrations.RemoveField(
            model_name='channelinfo',
            name='isnew',
        ),
        migrations.RemoveField(
            model_name='channelinfo',
            name='status',
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='index',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='isnew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='status',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Busy'), (3, 'Full'), (0, 'Stop'), (-1, 'Hide')], default=0),
        ),
    ]
