# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20160613_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('status', models.IntegerField(choices=[(0, 'Clear'), (1, 'White'), (2, 'Black')], default=0)),
            ],
        ),
    ]
